name: Azure Pipelines
variables:
  python.version: '3.7.6'
  azureServiceConnectionId: 'myserviceconnection'
  webAppName: 'Ad-AppService'
  resourcegroupname: 'Azuredevops'
  storageaccountname: 'storage5132022'
  containername: 'container5132022'
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: myAgentPool
    steps:
    # Needed for Terraform VM deployment
    # - task: InstallSSHKey@0
    #   inputs:
    #     knownHostsEntry: 'KNOWN_HOSTS_STRING'
    #     sshPublicKey: 'PUBLIC_KEY'
    #     sshKeySecureFile: 'id_rsa'
    - task: 'charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0'
      displayName: "Install Terraform"
      inputs:
        terraformVersion: '1.1.9'
    - task: 'ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2'
      displayName: 'Terraform init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environment/test'
        backendServiceArm: '$(azureServiceConnectionId)'
        backendAzureRmResourceGroupName: '$(resourcegroupname)'
        backendAzureRmStorageAccountName: '$(storageaccountname)'
        backendAzureRmContainerName: '$(containername)'
        backendAzureRmKey: 'terraform.state'
      
    - task: 'ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2'
      displayName: 'Terraform sol plan'
      inputs:
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environment/test'
        environmentServiceNameAzureRM: '$(azureServiceConnectionId)'

    - task: 'ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV2@2'
      displayName: 'Terraform apply'
      inputs:
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/environment/test'
        environmentServiceNameAzureRM: '$(azureServiceConnectionId)'  
    - task: ArchiveFiles@2
      displayName: 'Archive FakeRestAPI'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automatedtesting/jmeter/fakerestapi'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip'
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)-fakerestapi.zip
      displayName: 'Upload Package'
      artifact: drop-fakerestapi
- stage:
  jobs:
  - deployment: FakeRestAPI
    pool:
      name: myAgentPool
    environment: 'TEST'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appName: $(webAppName)
              appType: webApp
              package: $(Pipeline.Workspace)/drop-fakerestapi/$(Build.BuildId)-fakerestapi.zip
- stage: Test
  jobs:
  - job: jmeter
    pool:
      name: myAgentPool
    steps:
    - task: JMeterInstaller@0
      inputs:
        jmeterVersion: '5.2.1'
    - task: Bash@3
      displayName: EnduranceTest
      inputs:
        targetType: 'inline'
        script: jmeter -n -t automatedtesting/jmeter/Endurance.jmx -l automatedtesting/jmeter/enduranceresults.jtl -e -o automatedtesting/jmeter/endurancereport

    - task: Bash@3
      displayName: StressTest
      inputs:
        targetType: 'inline'
        script: jmeter -n -t automatedtesting/jmeter/Stress.jmx  -l automatedtesting/jmeter/stressresults.jtl -e -o automatedtesting/jmeter/stressreport

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'automatedtesting/jmeter'
        ArtifactName: 'jmeter'
        publishLocation: 'Container'
  
  - job: Postman
    pool:
      name: myAgentPool
    steps:
    - task: CmdLine@2
      displayName: Install Newman
      inputs:
        script: 'sudo npm install -g newman'
        workingDirectory: $(System.DefaultWorkingDirectory)
    - task: CmdLine@2
      displayName: Regression Tests
      continueOnError: true
      inputs:
        script: 'newman run RegressionSuite.postman_collection.json -e environment.json -r cli,junitfull --reporter-junitfull-export RegressionReport.xml'
        workingDirectory: '$(System.DefaultWorkingDirectory)/automatedtesting/postman'
    - task: CmdLine@2
      displayName: Data Validation Tests
      continueOnError: true
      inputs:
        script: 'newman run DataValidation.postman_collection.json -e environment.json -r cli,junitfull --reporter-junitfull-export DataValidationReport.xml'
        workingDirectory: '$(System.DefaultWorkingDirectory)/automatedtesting/postman'
    - task: PublishPipelineArtifact@1

      displayName: Publish Newman logs

      inputs:

        targetPath: '$(System.DefaultWorkingDirectory)/automatedtesting/postman'

        artifactName: 'drop-newman-logs'
    - task: PublishTestResults@2
      displayName: Publish Postman Test Result
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '$(System.DefaultWorkingDirectory)/automatedtesting/postman/*.xml'
 
  - job: Selenium
    pool:
      name: myAgentPool
    steps:
    - task: Bash@3
      displayName: Selenium
      inputs:
              targetType: 'inline'
              script: |
                wget https://chromedriver.storage.googleapis.com/101.0.4951.15/chromedriver_linux64.zip
                unzip chromedriver_linux64.zip
                sudo mv chromedriver /usr/bin/chromedriver
                sudo chown root:root /usr/bin/chromedriver
                sudo chmod +x /usr/bin/chromedriver
                python3 automatedtesting/selenium/login.py > logs.log
                cat logs.log
                sudo mv logs.log $(System.DefaultWorkingDirectory)/automatedtesting/selenium
    - task: ArchiveFiles@2
      displayName: Archive Selenium
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/automatedtesting/selenium'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(System.DefaultWorkingDirectory)/selenium-$(Build.BuildId).zip'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'automatedtesting/selenium'
        ArtifactName: 'selenium'
        publishLocation: 'Container'


  # - deployment: VMDeploy
  #   displayName: NAME
  #   environment:
  #     name:  ENVIRONMENT NAME
  #     resourceType: VirtualMachine
  #     tags: TAG NAME
  #   strategy:
  #     runOnce:
  #       deploy:
  #         steps:
  #         - task: Bash@3
  #           inputs:
  #             targetType: 'inline'
  #             script: |
  #               #! /bin/bash
                
  #               sudo apt-get upgrade -y
  #               sudo apt-get install python3-pip -y
  #               sudo apt-get install unzip -y
  #               sudo apt-get install -y chromium-browser
  #               pip3 install selenium
  #               export PATH=$PATH:some/path


